source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Packathon_Example', :exclusive => true do
  pod "Packathon", :path => "../"
end

target 'Packathon_Tests', :exclusive => true do
  pod "Packathon", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
